CREATE TABLE str_test(
MEMBER_ID VARCHAR(60) PRIMARY KEY,
NAME VARCHAR(60) NOT NULL);

INSERT INTO str_test(MEMBER_ID, NAME) VALUES
('1101', 'David'),
('1102', 'Michael'),
('1003', 'Jane');

SELECT LOWER(NAME) FROM str_test;
SELECT UPPER(NAME) FROM str_test;

# DUAL은 특수한 가상 테이블
SELECT TRIM(' GOOD ') FROM DUAL;
SELECT TRIM(LEADING '가' FROM '가나다라') FROM DUAL;
SELECT TRIM(TRAILING '라' FROM '가나다라') FROM DUAL;
SELECT TRIM(BOTH '가' FROM '가나다라가') FROM DUAL;

# TRIM 연습하기
SELECT TRIM(' HELLO  ') AS result FROM DUAL;
SELECT TRIM(LEADING FROM '     MYSQL     ') AS result FROM DUAL;
SELECT TRIM(TRAILING FROM '     MYSQL     ') AS result FROM DUAL;
SELECT TRIM('x' FROM 'xxxHELLOxxx') AS result FROM DUAL;
SELECT TRIM(LEADING '0' FROM '000GOOD') AS result FROM DUAL;
SELECT TRIM(TRAILING '0' FROM 'HELLO00000') AS result FROM DUAL;

# LTRIM 연슶하기
SELECT LTRIM('가나다라','가') FROM DUAL;

SELECT REPLACE('GOOD MORNING', 'MORNING', 'MARU') AS result FROM DUAL;

SELECT ABS(-2) FROM DUAL;

# 나머지 구하기
SELECT MOD(9,2) FROM DUAL;

# 반올림
SELECT ROUND(2.676, 1) FROM DUAL;

SELECT SIGN(2.3) FROM DUAL;
SELECT SIGN(-90) FROM DUAL;

SELECT CEIL(2.3) FROM DUAL;
SELECT CEIL(6.5) FROM DUAL;

SELECT FLOOR(2.3) FROM DUAL;
SELECT FLOOR(6.3) FROM DUAL;

