CREATE TABLE test_table
(EMPNO INT PRIMARY KEY,
ENAME VARCHAR(60) NOT NULL,
JOB VARCHAR(60) NOT NULL,
SAL INT NOT NULL,
COMM INT);

INSERT INTO test_table VALUES
(1111, 'SMITH', 'CLERK', 800, NULL),
(2222,'ALLEN', 'SALESMAN', 1600, 300),
(3333, 'WARD', 'SALESMAN', 2000, 500),
(4444, 'JONES', 'MANAGER',2900, NULL);

SELECT * FROM test_table;

CREATE TABLE emp
(EMPNO INT PRIMARY KEY,
ENAME VARCHAR(60) NOT NULL,
MGR INT);

INSERT INTO emp VALUES
(1111,'SMITH',7902),
(2222,'ALLEN',7689),
(3333, 'WARD',7689),
(4444, 'JONES',7839);

SELECT * FROM emp;

SELECT EMPNO, MGR, NULLIF(MGR,7689) AS NM FROM emp;

CREATE TABLE MOVIE(
MOVIE_CODE INT PRIMARY KEY
);

INSERT INTO MOVIE(MOVIE_CODE) VALUES
(1),
(2),
(3),
(4);

SELECT * FROM MOVIE;

SELECT MOVIE_CODE,
CASE
WHEN MOVIE_CODE = 1 THEN 'COMEDY'
WHEN MOVIE_CODE = 2 THEN 'SF'
WHEN MOVIE_CODE = 3 THEN 'ACTION'
ELSE 'TEC'
END AS MOVIE_GENRE
FROM MOVIE;

SELECT MOVIE_CODE,
CASE MOVIE_CODE
WHEN 1 THEN 'COMEDY'
WHEN 2 THEN 'SF'
WHEN 3 THEN 'ACTION'
ELSE 'ETC'
END AS MOVEI_GENRE
FROM MOVIE;